"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONTRACTOR_STATUSES = exports.DIRECTOR_LOAN_TRANSACTION_TYPES = exports.TRANSACTION_TYPES = exports.PROJECT_STATUSES = exports.ORGANIZATION_ROLES = void 0;
exports.ORGANIZATION_ROLES = ["OWNER", "ADMIN", "FINANCE", "PROJECT_MANAGER", "MEMBER"];
exports.PROJECT_STATUSES = ["PLANNED", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED"];
exports.TRANSACTION_TYPES = ["INCOME", "EXPENSE", "TRANSFER", "ADJUSTMENT"];
exports.DIRECTOR_LOAN_TRANSACTION_TYPES = ["DRAWDOWN", "REPAYMENT", "ADJUSTMENT"];
exports.CONTRACTOR_STATUSES = ["ACTIVE", "INACTIVE", "ON_HOLD"];
//# sourceMappingURL=index.js.map